### ISSUE TITLE
Feature Request: 豆瓣支持城市选择

### ISSUE THREAD

**Issue by kezhenxu94** [kezhenxu94/house-renting#1]
目前豆瓣只有广州天河区租房小组，希望添加城市选择的功能。

由于豆瓣上有非常多租房小组，且豆瓣没有穷举的列表或接口，而普遍认为豆瓣找房子比较靠谱（大都是租客或房东合租/直租），因此需要找一个方式来实现豆瓣的城市选择。

**Comment by popskf** [comment]
请支持"千居Spacious".

**Comment by popskf** [comment]
If support "千居Spacious" in feature, that will be Great!

**Comment by kezhenxu94** [comment]
@popskf I think it would be better to open another issue, anyway I'll work on it whenever I got some time.

**Comment by liguobao** [comment]
@kezhenxu94 豆瓣租房小组没有分类的,全靠人工筛选...

**Comment by liguobao** [comment]
https://www.zhihu.com/question/39733627

@kezhenxu94  这个帖子有部分的豆瓣租房数据,如果你要的话,我也可以给一份我现在维护的豆瓣租房小组数据给你.

@popskf https://woyaozufang.live/Home/HouseList?cityname=%E9%A6%99%E6%B8%AF

"千居Spacious" on https://woyaozufang.live
