### ISSUE TITLE
elasticsearch 换源

### ISSUE THREAD

**Issue by g10guang** [kezhenxu94/house-renting#16]
[elasticsearch hub.docker.com](https://hub.docker.com/_/elasticsearch/) 已经明确声明不再维护 elasticsearch offical 源了，所以你应该把 elasticsearch 的镜像换一个，换成 elasticsearch 官方维护的。

但是 elasticsearch 官方的源需要翻墙，国内好像不能够直接访问。

**Comment by kezhenxu94** [comment]
@g10guang 好，谢谢提醒，我今天抽空看看

**Comment by kezhenxu94** [comment]
@g10guang 换好了, 欢迎测试提 bug
