### ISSUE TITLE
城市设置没生效

### ISSUE THREAD

**Issue by pop9006** [kezhenxu94/house-renting#18]
>在a58.py和lianjia.py中只设置啦 cities = (u'北京')，但是得到的数据里面还是广州的.

而且很多时候只有douban的数据,lianjia的数据没见过, 我按照配置的流程走的, 全程也没有报错, 最后得到的数据不对. 
对这套工具不是熟悉, 也不知道哪个是重新获取数据？ 执行最初的 
docker-compose up --build -d这个吗？

**Comment by kezhenxu94** [comment]
@pop9006 如果你修改城市之前运行过了 
```
docker-compose up --build -d
```
在修改之后要重新启动，重新启动要用
```
docker-compose down
```
先停止原来的服务，再用最初的命令启动

如果没有链家和58的数据，可以用
```
docker logs lianjia
```
或
```
docker logs 58
```
看一下日志

**Comment by kezhenxu94** [comment]
@pop9006 如果你只要链家和58的数据，可以用

```
docker-compose up --build -d lianjia 58 kibana
```

只启动链家和58，如果原来已经跑了不用的数据，直接把 data 目录下的 elasticsearch 目录和 redis 目录删除，再重新启动即可

**Comment by pop9006** [comment]
多谢回复 看了下log, 我把cities = (u'北京')改成cities = (u'北京',) 能刷出数据啦

**Comment by kezhenxu94** [comment]
@pop9006 :wink: 好的，这个问题我应该再更新一下文档，那我可以把这个issue关咯
