### ISSUE TITLE
Feature Request: Support 千居Spacious

### ISSUE THREAD

**Issue by kezhenxu94** [kezhenxu94/house-renting#2]
https://www.spacious.hk/zh-tw/hong-kong

**Comment by liguobao** [comment]
https://woyaozufang.live/Home/HouseList?cityname=%E9%A6%99%E6%B8%AF

我这边做了千居数据集成,逃....
@kezhenxu94 

楼主不要打我.

**Comment by popskf** [comment]
Triple Six!
