### ISSUE TITLE
docker启动失败

### ISSUE THREAD

**Issue by lx308033262** [kezhenxu94/house-renting#20]
ERROR: error pulling image configuration: Get https://d2iks1dkcwqcbx.cloudfront.net/docker/registry/v2/blobs/sha256/38/3822ba554fe95f9ef68baa75cae97974135eb6aa8f8f37cadf11f6a59bde0139/data?Expires=1527842196&Signature=CHe3gZGVa~cy390rPxw-bobSFPU5boKRbQw4SqI6k8OgTvY~8BRuU-91Hbx8qPf~gt47ygwyXzmpidNHkh6eu6UmY0WBtABCFvQcy0cMalC9N5X7tT4LwgwsqykscMf3esBdIPTjQyk6g-c7ZEFGp1ox4OqW1dSOZHl9HG4Ke3L4D6ldtXdMPbdsZjQMlb5x3DObnQd2P4wRJnXHnjyiMaRrf~GUmg~iSuPDNXHcrRC0xbzkCmcj4cF2s4DmWFlXzouTuKZwZRJbJZ1uyo88DW417N~b~Df6jQHtG5P8qoATZ04UsU2R0yAeXlqgwsvlXp68TgUm5vy2uAt7TCN2sQ__&Key-Pair-Id=APKAIVAVKHB6SNHJAJQQ: net/http: TLS handshake timeout

 - 操作系统(OS): curl 
ubuntu 16.04

 - Docker:
root@zhanghao-X555LI:/usr/local/src/house-renting# docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64
 Experimental: false

这个镜像是不是得翻墙

**Comment by kezhenxu94** [comment]
😂不好意思，因为我一直开着 VPN，没有考虑到这个，如果你没有 VPN 的话，把 `docker-compose.yml` 中的
**`image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4`** 和 **`image: docker.elastic.co/kibana/kibana-oss:6.2.4`** 换成 `image: elasticsearch` 和 `image: kibana`

**Comment by kezhenxu94** [comment]
长时间没有反馈，将关闭 issue
