### ISSUE TITLE
Google搜索引擎的搜索技巧足够寻找住房信息

### ISSUE THREAD

**Issue by g10guang** [kezhenxu94/house-renting#22]
使用 site、""、* 模糊搜索等足以寻找足够的住房信息。

**Comment by g10guang** [comment]
或者说我想知道改仓库实现了哪些不能通过 Google 寻找的租房信息。

**Comment by kezhenxu94** [comment]
该项目还有一些其他的功能有待开发，作者之所以引入 ES 和 Kibana，除了方便信息展示之外，还有一个原因是考虑到一些数据分析的朋友可能会想要使用这个仓库来做一些数据分析的学习（如 Kibana 的一些可视化分析）。

我不会关闭这个 Issue，如果有其他朋友使用这个仓库做了一些除找房子之外的作用，如分析各地区租房价格分布等，欢迎来这里讨论分享。

**Comment by g10guang** [comment]
@kezhenxu94 之后我思考过，你这个项目最应该有的功能应该是：

- 可视化
- 过滤垃圾信息

我认为这是 google 等搜索引擎无法做到的。

对于垃圾消息，我看到 58 和自如等平台深圳租房的价格差异太大，不知道如何辨别真假信息~~很迷~~。

我对 scrapy 和 elasticsearch 数据做可视化方面没太多了解，所以也不能给出有建设性的意见。

最后，我希望本仓库的核心目的应该是帮助有需要的人找到合适的房子，而 docker、scrapy、elasticsearch 的技术介绍等我觉得都是次要的。BTW，你是 master，最终仓库的走向完全取决于你。
