### ISSUE TITLE
ModuleNotFoundError: No module named 'scrapy.conf'

### ISSUE THREAD

**Issue by dingyuanhong2006** [kezhenxu94/house-renting#32]
## Bug 描述 (Describe the bug)
    from scrapy.conf import settings
ModuleNotFoundError: No module named 'scrapy.conf'

## 如何重现 (To Reproduce)
基于win10 , 编译执行 scrapy crawl lianjia

## 桌面环境 Desktop (please complete the following information)

-  操作系统(OS): win10

-  Python: 3.7

-  Scrapy:1.7.3

-  Redis:

-  Elastic search:

-  Kibana:

## 附加信息 (Additional context)

> 添加有利于我们排查问题的附加信息. (Add any other context about the problem here.)

**Comment by dingyuanhong2006** [comment]
代码里有几个文件引用settings文件， 能否通过from_crawler的方式来使用settings 中的全局变量
    @classmethod
    def from_crawler(cls, crawler):
        return cls(
            redis_host = crawler.settings.get('REDIS_HOST'),
            redis_port = crawler.settings.get('REDIS_PORT')
        )

**Comment by kezhenxu94** [comment]
> 代码里有几个文件引用settings文件， 能否通过from_crawler的方式来使用settings 中的全局变量
> @classmethod
> def from_crawler(cls, crawler):
> return cls(
> redis_host = crawler.settings.get('REDIS_HOST'),
> redis_port = crawler.settings.get('REDIS_PORT')
> )

@dingyuanhong2006 可以试试看
