### ISSUE TITLE
设置了cities=(深圳,) 但爬出来的都是广州的好像？

### ISSUE THREAD

**Issue by Paulswith** [kezhenxu94/house-renting#35]
## 截图 (Screenshots)

> 如果有截图的话, 加上你遇到 Bug 的截图 (If applicable, add screenshots to help explain your problem).

![Screenshot from 2020-11-24 11-55-22](https://user-images.githubusercontent.com/24262233/100046848-04ed8800-2e4c-11eb-8a65-c90ab2b82fe4.png)
![Screenshot from 2020-11-24 11-56-48](https://user-images.githubusercontent.com/24262233/100053237-906e1580-2e5a-11eb-83ee-dd9865885e02.png)

## 桌面环境 Desktop (please complete the following information)

-  操作系统(OS): Ubuntu 20

通过 Docker 运行:

-  Docker:   是

**Comment by Paulswith** [comment]
看了下，douban.py 固定了天河的一个讨论组的地址

**Comment by kezhenxu94** [comment]
> 看了下，douban.py 固定了天河的一个讨论组的地址

是的, 可以帮忙加一个地址 🙇
