### ISSUE TITLE
请添加更多说明信息

### ISSUE THREAD

**Issue by g10guang** [kezhenxu94/house-renting#5]
1. Python版本要求；翻了 Dockerfile 才发现是 Python2
2. requirements.txt 方便通过 `pip install requirements.txt`安装所需要的依赖
3. 为什么不直接做一个 docker 镜像呢？

**Comment by kezhenxu94** [comment]
感谢提意见

1. 已经添加了 Wiki 页面, 增加了详细的说明和安装说明;
2. 增加了 requirements.txt 文件;
3. 项目涉及多个服务, 目前已经提供了 docker-compose 方式, 后续再考虑直接做一个 docker 镜像;
