### ISSUE TITLE
Let's migrate to Py3

### ISSUE THREAD

**Issue by popskf** [kezhenxu94/house-renting#9]
Looks like we are more interesting in py3(see other issues), then let's migrate it to py3

**Comment by cclauss** [comment]
https://github.com/kezhenxu94/house-renting/blob/master/crawler/house_renting/items.py#L46-L49

In Python 3, you can have a __u'string'__ and an __r'string'__ but a __ur'string'__ is a Syntax Error.

flake8 testing of https://github.com/kezhenxu94/house-renting on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./crawler/house_renting/items.py:46:46: E999 SyntaxError: invalid syntax
    minutes_ago = re.compile(ur'.*?(\d+)分钟前.*').search(value)
                                             ^
1     E999 SyntaxError: invalid syntax
1
```

**Comment by cclauss** [comment]
On Python 2, can we try the following?
1. Convert these __ur'strings'__ to __r'strings'__ and see if the code functions as expected and then
2. Convert these __ur'strings'__ to __u'strings'__ and see if the code functions as expected

My guess is that one of these will work as expected and the other will not.

**Comment by kezhenxu94** [comment]
@cclauss now can we say this project is compatible with Python3 and Python2 ?

**Comment by kezhenxu94** [comment]
@cclauss Great. I'll consider closing this issue
